#服务器配置
server:
  port: 2323
  servlet:
    context-path: /baidutts
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 30000

#百度API的鉴权信息
baidu:
  app-id:
  api-Key:
  secret-Key:

#系统每天的可用次数
tts:
  app-total: 5000
  user-total: 50


